const char* fragment_source = ""
	"" "\n"
	"#version 330 core" "\n"
	"" "\n"
	"in vec3 Color;" "\n"
	"" "\n"
	"out vec4 out_color;" "\n"
	"" "\n"
	"void main()" "\n"
	"{" "\n"
	"\tout_color = vec4(Color, 1.0);" "\n"
	"}" "\n"
	"" "\n"
	"" "\n"
	"" "\n"
	"";
